fix: `addToolResult` when there is multiple (parallel) tool calls
Yonom/assistant-ui pull request #643
Opened 2024-08-04 21:51 UTC by Rajaniraiyn

this ensures that all tool calls in an assistant message will have a corresponding result before performing round trip. without this for most ai providers they will throw an error

2024-08-04 22:06 UTC, Yonom requested changes
I am not able to reproduce the bug you specify... 

Furthermore, this code removes the added check (why?) and the added check is already in shouldContinue (does that one not work?)

2024-08-04 22:06 UTC, Yonom commented on packages/react/src/runtimes/local/LocalThreadRuntime.tsx
> +      (c) => c.type !== "tool-call" || c.result,
@Rajaniraiyn shouldContinue already checks for all tool calls having a result. this seems to be a duplicate check of the same thing

https://github.com/Yonom/assistant-ui/blob/c92547de23b878ec088f7c888dab4d1b3db1756e/packages/react/src/runtimes/local/shouldContinue.tsx#L6

2024-08-04 22:06 UTC, Yonom commented on packages/react/src/runtimes/local/LocalThreadRuntime.tsx
> -    let added = false;
Why is this added check removed?

It checks for repeat calls to addToolResult() to ensure that a roundtrip is only triggered if a tool result is added (and not updated)

2024-08-04 22:32 UTC, Yonom commented
There is a adjacent bug that I found while testing for this. 

If a message has pending tool calls; one can send new messages via the composer. I am fixing this in #644

2024-08-05 14:01 UTC, Rajaniraiyn commented
Closing this PR as it has duplicate checks and there is a better way to do the tool execution via `useAssistantTool` instead of `useAssistantToolUI`

2024-08-05 14:01 UTC, closed without merging

2024-08-05 17:22 UTC, Yonom commented
@Rajaniraiyn thank you for the submission! I really appreciate your efforts :)